Repository SOPT-all/35-COLLABORATION-WEB-AMAZON, pull requests merged in 2024-11, with the labels that each got.

#5 [setting/#1] router setting
  amazon/package.json
  amazon/src/App.tsx
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/pages/home/Home.tsx
  amazon/src/pages/searchResult/SearchResult.tsx
  amazon/src/routes/Router.tsx
  amazon/yarn.lock
Labels: ⚙️ Setting, 🫐 린아

#3 [Setting/#2] emotion 설치 및 스타일 초기세팅 완성
  amazon/index.html
  amazon/package.json
  amazon/src/App.tsx
  amazon/src/styles/GlobalStyles.ts
  amazon/src/styles/reset.ts
  amazon/src/styles/theme.ts
  amazon/tsconfig.app.json
  amazon/vite.config.ts
  amazon/yarn.lock
Labels: ⚙️ Setting, 🍋 화랑

#9 [Feat/#7] 메인캐러셀 완성
  amazon/package.json
  amazon/public/svg/ic_banner_leftArrow.svg
  amazon/public/svg/ic_banner_rightArrow.svg
  amazon/src/App.tsx
  amazon/src/assets/images/.keep
  amazon/src/assets/images/img_banner1.svg
  amazon/src/assets/images/img_banner2.svg
  amazon/src/assets/images/img_banner3.svg
  amazon/src/assets/images/img_banner4.svg
  amazon/src/assets/images/img_banner5.svg
  amazon/src/assets/svg/IcBannerLeftArrow.tsx
  amazon/src/assets/svg/IcBannerRightArrow.tsx
  amazon/src/assets/svg/Vite.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/assets/svgs/react.svg
  amazon/src/components/common/MainCarousel/MainCarousel.style.ts
  amazon/src/components/common/MainCarousel/MainCarousel.tsx
  amazon/src/components/common/index.ts
  amazon/src/pages/Dev/Dev.style.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/pages/home/Home.tsx
  amazon/src/pages/searchResult/SearchResult.tsx
  amazon/src/routes/Router.tsx
  amazon/tsconfig.app.json
  amazon/tsconfig.node.json
  amazon/vite.config.ts
  amazon/yarn.lock
Labels: ✨ Feature, 🍋 화랑

#11 [Feat/#8] 브레드 컴포넌트 완성
  amazon/.eslintrc.cjs
  amazon/public/svg/ic_bread_arrow.svg
  amazon/src/assets/svg/IcBreadArrow.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/Breadcrumb/Breadcrumb.style.ts
  amazon/src/components/common/Breadcrumb/Breadcrumb.tsx
  amazon/src/components/common/index.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/styles/theme.ts
Labels: ✨ Feature, 🍉 다현

#13 [Feat/#4] 서치 페이지 상품 카드 컴포넌트
  .DS_Store
  amazon/public/svg/ic_bestseller.svg
  amazon/public/svg/ic_cart.svg
  amazon/public/svg/ic_chevronRight.svg
  amazon/public/svg/ic_freedelivery.svg
  amazon/public/svg/ic_star.svg
  amazon/public/svg/ic_vector 120.svg
  amazon/src/assets/svg/IcBestseller.tsx
  amazon/src/assets/svg/IcCart.tsx
  amazon/src/assets/svg/IcChevronRight.tsx
  amazon/src/assets/svg/IcFreedelivery.tsx
  amazon/src/assets/svg/IcStar.tsx
  amazon/src/assets/svg/IcVector120.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/ProductCard/ProductCard.style.ts
  amazon/src/components/common/ProductCard/ProductCard.tsx
  amazon/src/components/common/ProductList/ProductList.style.ts
  amazon/src/components/common/ProductList/ProductList.tsx
  amazon/src/components/common/index.ts
  amazon/src/constants/index.ts
  amazon/src/constants/mocks/products.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/utils/.keep
  amazon/src/utils/formatDeliveryDate.tsx
  amazon/src/utils/index.ts
Labels: ✨ Feature, 🥝 찬영

#19 [Feat/#12] 서치바 구현
  amazon/public/svg/ic_close.svg
  amazon/public/svg/ic_header_search.svg
  amazon/public/svg/ic_searchbar.svg
  amazon/src/assets/svg/IcClose.tsx
  amazon/src/assets/svg/IcHeaderSearch.tsx
  amazon/src/assets/svg/IcSearchbar.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/SearchBar/SearchBar.style.ts
  amazon/src/components/common/SearchBar/SearchBar.tsx
  amazon/src/components/common/index.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/utils/constants/mocks/recentSearches.ts
  amazon/src/utils/index.ts
Labels: ✨ Feature, 🍉 다현

#20 [Feat/#18] 서치페이지 sorting bar 컴포넌트 구현
  amazon/src/assets/svg/IcBtnPage.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/SearchBar/SearchBar.style.ts
  amazon/src/components/common/SearchBar/SearchBar.tsx
  amazon/src/components/common/SortingBar/SortingBar.style.ts
  amazon/src/components/common/SortingBar/SortingBar.tsx
  amazon/src/components/common/index.ts
  amazon/src/constants/index.ts
  amazon/src/constants/mocks/recentSearches.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/styles/theme.ts
  amazon/src/utils/index.ts
Labels: ✨ Feature, 🥝 찬영

#26 [Feat/#17] horizontal scroll 컴포넌트 구현
  amazon/public/image/mainScrolls/img_main_scroll_card22.png
  amazon/public/image/mainScrolls/img_main_scroll_card27.png
  amazon/public/image/mainScrolls/img_main_scroll_card28.png
  amazon/public/image/mainScrolls/img_main_scroll_card29.png
  amazon/public/image/mainScrolls/img_main_scroll_card30.png
  amazon/public/image/mainScrolls/img_main_scroll_card31.png
  amazon/public/image/mainScrolls/img_main_scroll_card32.png
  amazon/public/image/mainScrolls/img_main_scroll_card70.png
  amazon/public/image/mainScrolls/img_main_scroll_card72.png
  amazon/public/image/mainScrolls/img_main_scroll_card73.png
  amazon/public/image/mainScrolls/img_main_scroll_card74.png
  amazon/public/image/mainScrolls/img_main_scroll_card75.png
  amazon/public/svg/ic_horizonScroll_leftArrow.svg
  amazon/public/svg/ic_horizonScroll_rightArrow.svg
  amazon/src/assets/svg/IcHorizonScrollLeftArrow.tsx
  amazon/src/assets/svg/IcHorizonScrollRightArrow.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/HorizontalScroll/HorizontalScroll.style.ts
  amazon/src/components/common/HorizontalScroll/HorizontalScroll.tsx
  amazon/src/components/common/SearchBar/SearchBar.tsx
  amazon/src/components/common/index.ts
  amazon/src/constants/images/index.ts
  amazon/src/constants/index.ts
  amazon/src/pages/Dev/Dev.tsx
Labels: ✨ Feature, 🍋 화랑

#29 [Fix] 서치페이지 하단 뷰 코드리뷰 반영
  amazon/src/components/common/BottomRecommend/BottomRecommend.style.ts
Labels: 🥝 찬영, 🍷 Fix

#25 [Feat/#6] 필터 리스트 구현
  amazon/public/svg/ic_bottom_search.svg
  amazon/public/svg/ic_cart.svg
  amazon/public/svg/ic_close.svg
  amazon/public/svg/ic_freedelivery.svg
  amazon/public/svg/ic_header_search.svg
  amazon/public/svg/ic_searchbar.svg
  amazon/src/assets/svg/IcCheckBoxFilled.tsx
  amazon/src/assets/svg/IcCheckBoxUnfilled.tsx
  amazon/src/assets/svg/IcChevronDown.tsx
  amazon/src/assets/svg/IcChevronUp.tsx
  amazon/src/assets/svg/IcColorchipBlack.tsx
  amazon/src/assets/svg/IcColorchipBlue.tsx
  amazon/src/assets/svg/IcColorchipBrown.tsx
  amazon/src/assets/svg/IcColorchipGold.tsx
  amazon/src/assets/svg/IcColorchipGray.tsx
  amazon/src/assets/svg/IcColorchipGreen.tsx
  amazon/src/assets/svg/IcColorchipKhaki.tsx
  amazon/src/assets/svg/IcColorchipLightGreen.tsx
  amazon/src/assets/svg/IcColorchipNavy.tsx
  amazon/src/assets/svg/IcColorchipOrange.tsx
  amazon/src/assets/svg/IcColorchipPink.tsx
  amazon/src/assets/svg/IcColorchipPurple.tsx
  amazon/src/assets/svg/IcColorchipRed.tsx
  amazon/src/assets/svg/IcColorchipSilver.tsx
  amazon/src/assets/svg/IcColorchipSkyBlue.tsx
  amazon/src/assets/svg/IcColorchipViolet.tsx
  amazon/src/assets/svg/IcColorchipWhite.tsx
  amazon/src/assets/svg/IcColorchipYellow.tsx
  amazon/src/assets/svg/IcRemove.tsx
  amazon/src/assets/svg/IcVector129.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/FilterList/FIlterContainer.tsx
  amazon/src/components/common/FilterList/FilterCategory.style.ts
  amazon/src/components/common/FilterList/FilterCategory.tsx
  amazon/src/components/common/FilterList/FilterCondition.style.ts
  amazon/src/components/common/FilterList/FilterCondition.tsx
  amazon/src/components/common/FilterList/FilterList.style.ts
  amazon/src/components/common/FilterList/FilterList.tsx
  amazon/src/components/common/FilterList/FilterOption.style.ts
  amazon/src/components/common/FilterList/FilterOption.tsx
  amazon/src/components/common/FilterList/FilterPrice.style.ts
  amazon/src/components/common/FilterList/FilterPrice.tsx
  amazon/src/components/common/FilterList/SelectedFilter.style.ts
  amazon/src/components/common/FilterList/SelectedFilters.tsx
  amazon/src/components/common/index.ts
  amazon/src/constants/index.ts
  amazon/src/constants/mocks/filterCondition.ts
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/utils/index.ts
Labels: ✨ Feature, 🫐 린아

#35 [Feat/#34] Footer 컴포넌트 완성
  amazon/public/svg/ic_footer_check.svg
  amazon/public/svg/ic_footer_language.svg
  amazon/public/svg/ic_footer_logo.svg
  amazon/public/svg/ic_footer_moneyUnit.svg
  amazon/public/svg/ic_footer_nation.svg
  amazon/src/assets/svg/IcBestseller.tsx
  amazon/src/assets/svg/IcFooterCheck.tsx
  amazon/src/assets/svg/IcFooterLanguage.tsx
  amazon/src/assets/svg/IcFooterLogo.tsx
  amazon/src/assets/svg/IcFooterMoneyUnit.tsx
  amazon/src/assets/svg/IcFooterNation.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/Footer/Footer.style.ts
  amazon/src/components/common/Footer/Footer.tsx
  amazon/src/components/common/index.ts
  amazon/src/pages/Dev/Dev.tsx
Labels: ✨ Feature, 🍋 화랑

#38 [Feat/#33] 메인 페이지 UI 구현
  amazon/src/assets/svg/IcGradationBanner.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/BottomLoginRecommend/BottomLoginRecommend.style.ts
  amazon/src/components/common/FilterList/SelectedFilter.style.ts
  amazon/src/components/common/FilterList/SelectedFilters.tsx
  amazon/src/components/common/MainCarousel/MainCarousel.style.ts
  amazon/src/pages/ search/Search.tsx
  amazon/src/pages/Dev/Dev.tsx
  amazon/src/pages/home/Home.style.ts
  amazon/src/pages/home/Home.tsx
Labels: ✨ Feature, 🫐 린아

#41 [Feat/#36] 최근 검색어 api 연결
  amazon/package.json
  amazon/src/apis/client.ts
  amazon/src/apis/getSearchHistory.ts
  amazon/src/components/common/SearchBar/SearchBar.style.ts
  amazon/src/components/common/SearchBar/SearchBar.tsx
  amazon/src/constants/api.ts
  amazon/src/constants/index.ts
  amazon/src/pages/ search/Search.style.ts
  amazon/src/pages/ search/Search.tsx
  amazon/src/pages/home/Home.tsx
  amazon/yarn.lock
Labels: ✨ Feature, 🍋 화랑

#42 [feat/#39] 필터리스트 api 연결
  amazon/src/apis/fetchFilters.ts
  amazon/src/components/common/FilterList/FIlterContainer.tsx
  amazon/src/components/common/FilterList/FilterCategory.tsx
  amazon/src/components/common/FilterList/FilterCondition.tsx
  amazon/src/components/common/FilterList/FilterList.tsx
  amazon/src/components/common/FilterList/SelectedFilter.style.ts
  amazon/src/components/common/FilterList/SelectedFilters.tsx
Labels: ✨ Feature, 🫐 린아

#43 [Feat/#37] 장바구니 api 연결
  amazon/index.html
  amazon/public/svg/ic_cart_add.svg
  amazon/public/svg/ic_cart_hover.svg
  amazon/public/svg/ic_toast check.svg
  amazon/public/svg/ic_toast_x.svg
  amazon/src/apis/.keep
  amazon/src/apis/shoppingCart/deleteCart.ts
  amazon/src/apis/shoppingCart/postCart.ts
  amazon/src/assets/svg/IcCartAdd.tsx
  amazon/src/assets/svg/IcCartHover.tsx
  amazon/src/assets/svg/IcToastCheck.tsx
  amazon/src/assets/svg/IcToastX.tsx
  amazon/src/assets/svg/index.ts
  amazon/src/components/common/Header/Header.tsx
  amazon/src/components/common/ProductCard/ProductCard.style.ts
  amazon/src/components/common/ProductCard/ProductCard.tsx
  amazon/src/components/common/ProductList/ProductList.tsx
  amazon/src/components/common/ToastCheckCard/ToastCheckCard.style.ts
  amazon/src/components/common/ToastCheckCard/ToastCheckCard.tsx
  amazon/src/components/common/index.ts
  amazon/src/constants/mocks/products.ts
  amazon/src/context/cartContext.tsx
  amazon/src/hooks/.keep
  amazon/src/hooks/useToast.ts
  amazon/src/pages/Layout/Layout.tsx
  amazon/src/types/.keep
  amazon/src/types/productDataProps.ts
  amazon/yarn.lock
Labels: ✨ Feature, 🥝 찬영

#45 [Feat/#40] 검색 api 연결
  amazon/src/apis/getProducts.ts
  amazon/src/components/common/Header/Header.tsx
  amazon/src/components/common/ProductList/ProductList.tsx
  amazon/src/components/common/SearchBar/SearchBar.tsx
  amazon/src/components/common/SortingBar/SortingBar.tsx
  amazon/src/pages/ search/Search.tsx
Labels: ✨ Feature, 🍉 다현

#47 [Fix/#46] 장바구니 api 수정 및 헤더 연결
  src/App.tsx
  src/apis/fetchFilters.ts
  src/apis/shoppingCart/deleteCart.ts
  src/apis/shoppingCart/deleteCartCount.ts
  src/apis/shoppingCart/getCartCount.ts
  src/apis/shoppingCart/postCartCount.ts
  src/assets/svg/IcFreedelivery.tsx
  src/assets/svg/IcHamburger.tsx
  src/assets/svg/index.ts
  src/components/common/Header/Header.style.ts
  src/components/common/Header/Header.tsx
  src/components/common/ProductCard/ProductCard.tsx
  src/components/common/ProductList/ProductList.tsx
  src/components/common/ToastCheckCard/ToastCheckCard.style.ts
  src/components/common/ToastCheckCard/ToastCheckCard.tsx
  src/constants/api.ts
  src/constants/index.ts
  src/constants/mocks/products.ts
  src/hooks/useToast.ts
  src/types/index.ts
  src/types/productData.ts
  vite.config.js
Labels: 🥝 찬영, 🍷 Fix

#49 [Feat/#48] 서치 키워드 유지 및 검색 UI 개선
  src/components/common/Header/Header.style.ts
  src/components/common/Header/Header.tsx
  src/components/common/ProductList/ProductList.tsx
  src/components/common/SearchBar/SearchBar.tsx
  src/components/common/SortingBar/SortingBar.tsx
  src/pages/ search/Search.style.ts
  src/pages/ search/Search.tsx
Labels: ✨ Feature, 🍉 다현
